services:
  apache:
    container_name: project_be_apache 
    build: 
      context: ./
      dockerfile: ./backend/apache/Dockerfile
    restart: on-failure 
    ports:
      - "8080:80"
    volumes:
      - ./backend/laravel:/var/www/html
      - ./backend/apache/config/conf-available:/etc/apache2/conf-available
      - ./backend/apache/config/conf-enabled:/etc/apache2/conf-enabled
      - ./backend/apache/config/mods-available:/etc/apache2/mods-available
      - ./backend/apache/config/mods-enabled:/etc/apache2/mods-enabled
      - ./backend/apache/config/sites-available:/etc/apache2/sites-available
      - ./backend/apache/config/sites-enabled:/etc/apache2/sites-enabled
      - ./backend/apache/config/apache2.conf:/etc/apache2/apache2.conf
      - ./backend/apache/config/ports.conf:/etc/apache2/ports.conf
      - ./backend/apache/config/envvars:/etc/apache2/envvars
    environment:  
      DB_HOST: project_mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      CUSTOM_APACHE_LOG_DIR: ${CUSTOM_APACHE_LOG_DIR}
      DB_CONNECTION: mysql
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      - mysql
    networks:
      - project_network

  mysql:
    image: mysql:8.0
    container_name: project_mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${MYSQL_DATABASE}         
      MYSQL_USER: ${MYSQL_USER}                  
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    volumes:
      - project_SQL_database:/var/lib/mysql 
    ports:
      - "3306:3306"
    networks:
      - project_network

  laravel:
    image: php:8.3-cli
    container_name: project_be_laravel
    build:
      context: ./
      dockerfile: ./backend/laravel/Dockerfile
    restart: on-failure
    volumes:
      - ./backend/laravel/app:/var/www/html/app
      - ./backend/laravel/bootstrap/app.php:/var/www/html/bootstrap/app.php
      - ./backend/laravel/bootstrap/providers.php:/var/www/html/bootstrap/providers.php
      - ./backend/laravel/config:/var/www/html/config
      - ./backend/laravel/database:/var/www/html/database
      - ./backend/laravel/public:/var/www/html/public
      - ./backend/laravel/resources:/var/www/html/resources
      - ./backend/laravel/routes:/var/www/html/routes
      - ./backend/laravel/tests:/var/www/html/tests
      - ./backend/laravel/.env:/var/www/html/.env
      - ./backend/laravel/artisan:/var/www/html/artisan
      - ./backend/laravel/composer.json:/var/www/html/composer.json
    depends_on:
      - mysql
    networks:
      - project_network
    environment:  
      DB_HOST: project_mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_CONNECTION: mysql
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}

volumes:
  project_SQL_database:
  storage:
  bootstrap:

networks:
  project_network:
